### ISSUE TITLE
Generated code uses different path separators if built in Linux versus Windows (i.e. `/` versus `\\`)

### ISSUE THREAD

**Issue by rahmant3** [fin-language/fin#46]
Just want to say this tool is amazing! =) 

I have a minor issue with the way code is generated in finlang v0.3.0-alpha.

When code is generated, I'd like to use Jenkins to verify whether the files generated are any different to what was last committed using `git diff`. The problem I have is that Jenkins uses Linux to generate the code, versus my local workstation which is Windows. The generated code looks slightly different based on the platform due to the path separators (pay attention to the 3rd line in both excerpts).

Windows:
```
// AUTOGENERATED FILE. Do not modify this file manually, it will be overwritten.
// finlang v0.3.0-alpha generated this file for C# `sample.SampleClass` type.
// Source file: `sample\SampleClass.cs` (relative to C# solution).
```

Linux
```
// AUTOGENERATED FILE. Do not modify this file manually, it will be overwritten.
// finlang v0.3.0-alpha generated this file for C# `sample.SampleClass` type.
// Source file: `sample/SampleClass.cs` (relative to C# solution).
```

Can the code generator always use Linux-style separators please?

**Comment by adamfk** [comment]
Good call. Fixed in above commit. thanks!
