### ISSUE TITLE
Add support for `sizeof(u32)`, `sizeof(u16)`, etc

### ISSUE THREAD

**Issue by rahmant3** [fin-language/fin#50]
I have a code snippet like this where I want to find out the number of words in a buffer.
```cs
    public bool work_with_buffer(c_array<u8> buffer, u32 size)
    {
        math.unsafe_mode();
        
        u32 num_words = size / 4; <-- How to use sizeof(u32) instead of 4 ?
```

In C, I would normally use sizeof() (rather than the literal 4, but I couldn't find a way to do it. I think it would be helpful to have a way to get the size of types like u16, u32 so that we can do math with them.

**Comment by adamfk** [comment]
Ready in next release. 

We have basic support here: https://github.com/fin-language/fin/commit/06bc318c6e0bedb95474c522a84ae09cb82b2e1c#diff-7d36356b5db22267786da0c86a4c91c57798a404f44895b63a7c2a3e6922dc16

You can use it on fin integer primitive variables like this: `mem.size_of(my_u8)`.

You can can get size of fin integer types like this: `u8.SIZE`

There's no support yet for getting the size of class objects. Needs some thought as it isn't cross platform. The size of a class/struct depends on compiler and architecture...

To avoid issues with sizeof() on pointers, we get a bit lazy: https://github.com/fin-language/fin/blob/5df03e6d0ad3591d9207cc669bef231c201d201f/src/test/ExSln2/c99/gen/hal_SizeOfEx.c#L18

```c
uint8_t hal_SizeOfEx_calc_param_refs_sizes(uint8_t * a, int32_t * b)
{
    return sizeof(uint8_t /*a*/) + sizeof(int32_t /*b*/); // note generated doesn't return size of pointer
}
```

I think it looks OK though for now.
