### ISSUE TITLE
How to declare constants (e.g. `const` or `#define`)?

### ISSUE THREAD

**Issue by rahmant3** [fin-language/fin#51]
I have some constants and I'd like to place them at the beginning of my class for easy access. I've tried a few different variations to generate correct code.

This approach does not compile as u32 cannot be const.
```cs
class Sample {
    private const u32 CONST1 = 0xFFFFFFFF;
    private const u32 CONST2 = 0x22FFFFFF;
}
```

This approach generates code that creates CONST1 and CONST2 members in the object structure. If I create an empty constructor then it seems to initialize the members when the constructor is called. This is what I'm going with for now, but it technically uses up RAM unnecessarily.
```cs
class Sample {
    private readonly u32 CONST1 = 0xFFFFFFFF;
    private readonly u32 CONST2 = 0x22FFFFFF;

    public Sample() {}
}
```

This approach doesn't seem to generate the constant declarations (e.g. no `#define` or `static const CONST1 = 0xFFFFFFFF;`).
```cs
class Sample {
    private static readonly u32 CONST1 = 0xFFFFFFFF;
    private static readonly u32 CONST2 = 0x22FFFFFF;

    public Sample() {}
}
```

**Comment by adamfk** [comment]
Thanks for the report.

The next release will have support for constants implemented with defines.

Here's some examples: https://github.com/fin-language/fin/commit/41ea89bf81138a700bd646c7f4130fe7018cdd88#diff-53ad8b4b68d5c41b77b3f319273999096e7a187726a2d8562435ef29caf9423e

They can be added to interfaces and regular classes.
