### ISSUE TITLE
Issue using the "out" keyword with structures

### ISSUE THREAD

**Issue by rahmant3** [fin-language/fin#85]
I have a C# function like this:
```c#
bool GetDiagnostics(out Diagnostics info_out);
```
Where `Diagnostics` was an FFI class.

When I transpiled, it turned into this:
```c
bool (*GetDiagnostics)(void * self, sample_ns_CanDiagnostics * * info_out);
```

I was wanting something like this (without the extra '*'):
```c
bool (*GetDiagnostics)(void * self, sample_ns_CanDiagnostics * * info_out);
```

I believe the current behavior is not correct. 

For example in C# if I wrote code that used the function, it would fill the class with all of the data it needed, e.g.
```c#
Diagnostics diag = null;
if (obj.GetDiagnostics(out diag)) {
    if (null != diag) {
        // good to go
    }
}
```

NOTE: The `out` keyword works well for primitive types like `u32`, but it doesn't behave the way I would like for a class type.

**Comment by adamfk** [comment]
I think it does behave correctly at first glance. In C#, you use `out` on class parameters when you want to re-assign what `diag` points to. It then needs a pointer to the pointer so that it can affect the original pointer.

I think you actually want
```cs
bool GetDiagnostics(Diagnostics info_out);
```

**Comment by rahmant3** [comment]
Thinking about it some more I would agree. In C# I suppose it takes care of dynamically allocating memory for `diag`, so from Fin's perspective it would be ambiguous if it worked the other way.
